In [3]:
import numpy as np

In [11]:
#rank 1 array
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [13]:
#rank 2 array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [14]:
#array using tuple
arr3 = np.array((1,2,3))
print(arr3)

[1 2 3]


In [15]:
#indexing

In [18]:
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])
print("initial array: \n",arr)

initial array: 
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [21]:
slicedarr=arr[:2,::2]
print("first 2 rows, alternate element\n",slicedarr)

first 2 rows, alternate element
 [[-1.  0.]
 [ 4.  6.]]


In [23]:
index_arr = arr[[1,1,0,3],[3,2,1,0]]
print("specefic indexes\n ")
print("(1,3),(1,2),(0,1),(3,0)\n")
print(index_arr)

specefic indexes
 
(1,3),(1,2),(0,1),(3,0)

[0. 6. 2. 3.]


In [35]:
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

In [38]:
print ("Adding 1 to every element\n", a + 1)

Adding 1 to every element
 [[2 3]
 [4 5]]


In [39]:
print ("\nSubtracting 2 from each element\n", b - 2)


Subtracting 2 from each element
 [[ 2  1]
 [ 0 -1]]


In [41]:
print ("\nSum of all array elements: ", a.sum())


Sum of all array elements:  10


In [42]:
#random and slicing

In [36]:
arr2 = np.random.randint(1,100,(5,6))

In [25]:
arr2

array([[88, 48, 35, 64, 88, 68],
       [97, 11, 40, 16, 38, 55],
       [46, 95, 96, 95, 26, 43],
       [27, 97, 19, 99, 13, 57],
       [82, 47, 10, 71, 67,  2]])

In [26]:
arr2[2:4,2:4]

array([[96, 95],
       [19, 99]])

In [27]:
arr2[:-1]

array([[88, 48, 35, 64, 88, 68],
       [97, 11, 40, 16, 38, 55],
       [46, 95, 96, 95, 26, 43],
       [27, 97, 19, 99, 13, 57]])

In [31]:
arr2[:,0:5]

array([[88, 48, 35, 64, 88],
       [97, 11, 40, 16, 38],
       [46, 95, 96, 95, 26],
       [27, 97, 19, 99, 13],
       [82, 47, 10, 71, 67]])

In [43]:
x = np.array([1, 2])  
print("Integer Datatype: ")
print(x.dtype)  

Integer Datatype: 
int32


In [44]:
x = np.array([1.0, 2.0]) 
print("\nFloat Datatype: ")
print(x.dtype) 


Float Datatype: 
float64


In [46]:
x = np.array([1, 2], dtype = np.int64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
int64


In [49]:
x = np.array([1, 2], dtype = np.float64)   
print("\nForcing a Datatype: ")
print(x.dtype)


Forcing a Datatype: 
float64


In [56]:
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.int64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.int64) 

In [57]:
sum = np.add(arr1,arr2)
print("Addition of 2 arr\n ",sum)

Addition of 2 arr
  [[ 7 13]
 [ 4 14]]


In [59]:
sumof1 = np.sum(arr1)
sumofboth = np.sum(sum)
print("sum of elements of arr1: ",sumof1)
#print("\n")
print("sum of elements of both: ",sumofboth)

sum of elements of arr1:  19
sum of elements of both:  38


In [60]:
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)


Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [61]:
Trans_arr = arr1.T
print("\nArray: ")
print(arr1)
print("\nTranspose of Array: ")
print(Trans_arr)


Array: 
[[4 7]
 [2 6]]

Transpose of Array: 
[[4 2]
 [7 6]]


In [62]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [64]:
# Python program to demonstrate 
# the use of data type object with structured array.
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])
 
# x is a structured array with names and marks of students.
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64)
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
print("Grades of John are: ",x[1]['grades'])
print("Names are: ",x['name'])

('John', [6., 7.])
Grades of John are:  [6. 7.]
Names are:  ['Sarah' 'John']


In [70]:
import numpy as geek 
  
arr = geek.arange(9.0).reshape(3, 3) 
  
gfg = geek.vsplit(arr, 1) 
  
print (gfg) 

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]
